spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: arpat990708
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
  
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

file:
  upload-dir: ./uploads

jwt:
  secret: your-secret-key
  expiration: 86400  # 24小时，单位：秒

profiles:
  active: ${SPRING_PROFILES_ACTIVE:dev}